<<<<<<< HEAD
language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script: composer install -n

script: phpunit -c app
=======
sudo: false

language: node_js

node_js:
  - "0.10"
  
before_script:
  - npm install -g grunt-cli
>>>>>>> fb7bf15b389104ccb38b4b89c6d40ca949d0232f
